# 1/8 RxJava - Errror 연산자

** Reactive API를 사용하는 경우 Try Catch 구문으로 묶어도 에러를 잡지 못한다. **

![스크린샷 2022-01-09 오후 4.28.18.png](1.png)

![스크린샷 2022-01-09 오후 4.28.42.png](2.png)

→ 그러므로 error 처리 연산자를 통해 해결해준다

![스크린샷 2022-01-09 오후 4.29.33.png](3.png)

**onErrorReturn**

- 에러가 발생했을 때 에러를 의미하는 데이터로 대체할 수 있다
- onError 이벤트를 발생시키지 않는다

![스크린샷 2022-01-09 오후 4.35.52.png](4.png)

![스크린샷 2022-01-09 오후 4.36.23.png](5.png)

**onErrorResumeNext**

- 에러가 발생했을 때 에러가 의미하는 Observable로 대체할 수 있다
- Observable로 대체할 수 있으므로 데이터 교체와 더불어 에러 처리를 위한 추가 작업을 할 수 있다

![스크린샷 2022-01-09 오후 4.38.16.png](6.png)

![스크린샷 2022-01-09 오후 4.41.09.png](7.png)

**retry**

- 데이터 통지 중 에러가 발생했을 때, 데이터 통지를 재시도한다
- 즉, onError 이벤트가 발생하면 subscribe() 를 다시 호출하여 재구독한다

![스크린샷 2022-01-09 오후 4.43.24.png](8.png)

!! 에러가 발생한 시점의 데이터만 재호출하는 것이 아닌 처음부터 다시 불러온다